# Use the newer Travis-CI build templates based on the
# Debian Linux distribution "Xenial" release.
os: linux
dist: xenial
language: minimal
jobs:
  include:
    - stage: build
      services: docker
      install: true
      script: make -e REGISTRY=fred78290 -e TAG=dev container
    - stage: test
      services: docker
      install: true
      script: make test-in-docker
    - stage: deploy
      if: tag IS present OR commit_message =~ /\/ci-deploy/
      services: docker
      install: true
      script: make -e REGISTRY=fred78290 -e TAG=$TRAVIS_TAG container
      before_deploy:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      after_deploy:
        - docker push fred78290/vsphere-autoscaler:$TRAVIS_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
          repo: Fred78290/kubernetes-vmware-autoscaler
        file:
          - out/vsphere-autoscaler-darwin-amd64
          - out/vsphere-autoscaler-linux-amd64
