apiVersion: v1
kind: Namespace
metadata:
  name: vmware-ca-k8s
---
apiVersion: "nodemanager.aldunelabs.com/v1alpha1"
kind: "ManagedNode"
metadata:
  name: "vmware-ca-k8s-managed-01"
  namespace: "vmware-ca-k8s"
spec:
  controlPlane: true
  allowDeployment: false
  vcpus: 4
  memorySizeInMb: 4096
  diskSizeInMb: 20480
  labels:
  - demo-label.aldunelabs.com=demo
  - sample-label.aldunelabs.com=sample
  annotations:
  - demo-annotation.aldunelabs.com=demo
  - sample-annotation.aldunelabs.com=sample
  networks:
    -
      network: "VM Network"
      address: 10.0.0.80
      netmask: 255.255.255.0
      gateway: 10.0.0.1
    -
      network: "VM Private"
      address: 192.168.1.80
      netmask: 255.255.255.0
      gateway: 10.0.0.1
